### ISSUE TITLE
.bower.json bug

### ISSUE THREAD

**Issue by archasek** [flot/flot#1500]
Hi. There are 2 curly brackets at the end of file instead of one:

```
{
  "name": "Flot",
  "version": "0.8.3",
  "main": "jquery.flot.js",
  "dependencies": {
    "jquery": ">= 1.2.6"
  },
  "homepage": "https://github.com/flot/flot",
  "_release": "0.8.3",
  "_resolution": {
    "type": "version",
    "tag": "v0.8.3",
    "commit": "453b017cc5acfd75e252b93e8635f57f4196d45d"
  },
  "_source": "https://github.com/flot/flot.git",
  "_target": "^0.8.3",
  "_originalSource": "flot"
}}
```

**Comment by archasek** [comment]
And also I have regularly notifications like this:

> bower ENOENT        ENOENT: no such file or directory, lstat 'C:\archas\workspace\dashboard\web\bower_components\Flot\examples\axes-time-zones\tz\solar87'

**Comment by danielmariz** [comment]
That's weird cause I got this in one machine and another one not both running the same project.
One adds extra braces in the end of .bower.json file (}) which is causing the issue.
I'm trying to figure out how to fix it and do a pull request but couldn't find how flot generates this file because is not inside the project.

**Comment by danielmariz** [comment]
Try to do a `bower cache clean` and `bower install` to see if it'll be fixed @archasek

**Comment by Beakerboy** [comment]
#1571 related and fixed.
