### ISSUE TITLE
legend noColumns not available anymore in v3.0.0.

### ISSUE THREAD

**Issue by digimen-ch** [flot/flot#1658]
It looks like noColumns option is not available anymore in the latest version. I searched also the in the files flot.js and legend.js and didn't find anything. Did you forget to implement it? Or renamed?

**Comment by gorkovv** [comment]
Moreover. It still has a default black background! -(

**Comment by jondbennett** [comment]
First, I'm no export on Flot, having used it for only a few hours. However...
1) It seems that noColumns is still (at the time I'm writing this message) in the API documentation but is not actually supported any longer. Another forum user helped me with this, so that info comes from someone that actually knows what they are talking about.

2) I was also having the black-background in the legend problem. You need to provide the following in your CSS.

		.legendLayer .background {
			fill: rgba(255, 255, 255, 0.55);
			stroke: rgba(0, 0, 0, 0.85);
			stroke-width: 1;
		}

O course you can use any fill.stroke color you like.

--
Jon

**Comment by andrewdove1** [comment]
PR #1687
