### ISSUE TITLE
Ajax example not working

### ISSUE THREAD

**Issue by imabot2** [flot/flot#1731]
I download the zip file and tryed the examples. 

There is a problem with examples/ajax/index.html. Nothing appears in the graphics area and the following message is displayed in the console :

`jquery.js:8435 Access to XMLHttpRequest at 'file:///home/philippe/T%C3%A9l%C3%A9chargements/flot-master/examples/ajax/data-eu-gdp-growth.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.`

**Comment by brianehenry** [comment]
Hey imabot2,

I'm able to load the example without errors. I'm guessing that you are trying to use the example by just opening the HTML file in a browser, instead of hosting the example content with a web server. Try using a local web server like [http-server](https://www.npmjs.com/package/http-server) to serve the files.
